[
  { name: "ICHCHAPURAM", code: "001" },
  { name: "PALASA", code: "002" },
  { name: "TEKKALI", code: "003" },
  { name: "PATHAPATNAM", code: "004" },
  { name: "SRIKAKULAM", code: "005" },
  { name: "AMADALAVALASA", code: "006" },
  { name: "ETCHERLA", code: "007" },
  { name: "NARASANNAPETA", code: "008" },
  { name: "RAJAM", code: "009" },
  { name: "PALAKONDA", code: "010" },
  { name: "KURUPAM", code: "011" },
  { name: "PARVATHIPURAM", code: "012" },
  { name: "SALUR", code: "013" },
  { name: "BOBBILI", code: "014" },
  { name: "CHEEPURUPALLI", code: "015" },
  { name: "GAJAPATHINAGARAM", code: "016" },
  { name: "NELLIMARLA", code: "017" },
  { name: "VIZIANAGARAM", code: "018" },
  { name: "SRUNGAVARAPUKOTA", code: "019" },
  { name: "BHIMILI", code: "020" },
  { name: "VISAKHAPATNAM EAST", code: "021" },
  { name: "VISAKHAPATNAM SOUTH", code: "022" },
  { name: "VISAKHAPATNAM NORTH", code: "023" },
  { name: "VISAKHAPATNAM WEST", code: "024" },
  { name: "GAJUWAKA", code: "025" },
  { name: "CHODAVARAM", code: "026" },
  { name: "MADUGULA", code: "027" },
  { name: "ARAKU VALLEY", code: "028" },
  { name: "PADERU", code: "029" },
  { name: "ANAKAPALLE", code: "030" },
  { name: "PENDURTHI", code: "031" },
  { name: "YELAMANCHILI", code: "032" },
  { name: "PAYAKARAOPET", code: "033" },
  { name: "NARSIPATNAM", code: "034" },
  { name: "TUNI", code: "035" },
  { name: "PRATHIPADU(Visakhapatnam)", code: "036" },
  { name: "PITHAPURAM", code: "037" },
  { name: "KAKINADA RURAL", code: "038" },
  { name: "PEDDAPURAM", code: "039" },
  { name: "ANAPARTHY", code: "040" },
  { name: "KAKINADA CITY", code: "041" },
  { name: "RAMACHANDRAPURAM", code: "042" },
  { name: "MUMMIDIVARAM", code: "043" },
  { name: "AMALAPURAM", code: "044" },
  { name: "RAZOLE", code: "045" },
  { name: "GANNAVARAM", code: "046" },
  { name: "KOTHAPETA", code: "047" },
  { name: "MANDAPETA", code: "048" },
  { name: "RAJANAGARAM", code: "049" },
  { name: "RAJAHMUNDRY CITY", code: "050" },
  { name: "RAJAHMUNDRY RURAL", code: "051" },
  { name: "JAGGAMPETA", code: "052" },
  { name: "RAMPACHODAVARAM", code: "053" },
  { name: "KOVVUR", code: "054" },
  { name: "NIDADAVOLE", code: "055" },
  { name: "ACHANTA", code: "056" },
  { name: "PALACOLE", code: "057" },
  { name: "NARASAPURAM", code: "058" },
  { name: "BHIMAVARAM", code: "059" },
  { name: "UNDI", code: "060" },
  { name: "TANUKU", code: "061" },
  { name: "TADEPALLIGUDEM", code: "062" },
  { name: "UNGUTURU", code: "063" },
  { name: "DENDULURU", code: "064" },
  { name: "ELURU", code: "065" },
  { name: "GOPALAPURAM", code: "066" },
  { name: "POLAVARAM", code: "067" },
  { name: "CHINTALAPUDI", code: "068" },
  { name: "TIRUVURU", code: "069" },
  { name: "NUZVID", code: "070" },
  { name: "GANNAVARAM", code: "071" },
  { name: "GUDIVADA", code: "072" },
  { name: "KAIKALUR", code: "073" },
  { name: "PEDANA", code: "074" },
  { name: "MACHILIPATNAM", code: "075" },
  { name: "AVANIGADDA", code: "076" },
  { name: "PAMARRU", code: "077" },
  { name: "PENAMALURU", code: "078" },
  { name: "VIJAYAWADA WEST", code: "079" },
  { name: "VIJAYAWADA CENTRAL", code: "080" },
  { name: "VIJAYAWADA EAST", code: "081" },
  { name: "MYLAVARAM", code: "082" },
  { name: "NANDIGAMA", code: "083" },
  { name: "JAGGAYYAPETA", code: "084" },
  { name: "PEDAKURAPADU", code: "085" },
  { name: "TADIKONDA", code: "086" },
  { name: "MANGALAGIRI", code: "087" },
  { name: "PONNURU", code: "088" },
  { name: "VEMURU", code: "089" },
  { name: "REPALLE", code: "090" },
  { name: "TENALI", code: "091" },
  { name: "BAPATLA", code: "092" },
  { name: "PRATHIPADU", code: "093" },
  { name: "GUNTUR WEST", code: "094" },
  { name: "GUNTUR EAST", code: "095" },
  { name: "CHILAKALURIPET", code: "096" },
  { name: "NARASARAOPET", code: "097" },
  { name: "SATTENAPALLE", code: "098" },
  { name: "VINUKONDA", code: "099" },
  { name: "GURAJALA", code: "100" },
  { name: "MACHERLA", code: "101" },
  { name: "YERRAGONDAPALEM", code: "102" },
  { name: "DARSI", code: "103" },
  { name: "PARCHUR", code: "104" },
  { name: "ADDANKI", code: "105" },
  { name: "CHIRALA", code: "106" },
  { name: "SANTHANUTHALAPADU", code: "107" },
  { name: "ONGOLE", code: "108" },
  { name: "KANDUKUR", code: "109" },
  { name: "KONDAPI", code: "110" },
  { name: "MARKAPURAM", code: "111" },
  { name: "GIDDALUR", code: "112" },
  { name: "KANIGIRI", code: "113" },
  { name: "KAVALI", code: "114" },
  { name: "ATMAKUR", code: "115" },
  { name: "KOVUR", code: "116" },
  { name: "NELLORE CITY", code: "117" },
  { name: "NELLORE RURAL", code: "118" },
  { name: "SARVEPALLI", code: "119" },
  { name: "GUDUR", code: "120" },
  { name: "SULLURPETA", code: "121" },
  { name: "VENKATAGIRI", code: "122" },
  { name: "UDAYAGIRI", code: "123" },
  { name: "BADVEL", code: "124" },
  { name: "RAJAMPET", code: "125" },
  { name: "KADAPA", code: "126" },
  { name: "KODUR", code: "127" },
  { name: "RAYACHOTI", code: "128" },
  { name: "PULIVENDLA", code: "129" },
  { name: "KAMALAPURAM", code: "130" },
  { name: "JAMMALAMADUGU", code: "131" },
  { name: "PRODDATUR", code: "132" },
  { name: "MYDUKUR", code: "133" },
  { name: "ALLAGADDA", code: "134" },
  { name: "SRISAILAM", code: "135" },
  { name: "NANDIKOTKUR", code: "136" },
  { name: "KURNOOL", code: "137" },
  { name: "PANYAM", code: "138" },
  { name: "NANDYAL", code: "139" },
  { name: "BANAGANAPALLE", code: "140" },
  { name: "DHONE", code: "141" },
  { name: "PATTIKONDA", code: "142" },
  { name: "KODUMUR", code: "143" },
  { name: "YEMMIGANUR", code: "144" },
  { name: "MANTRALAYAM", code: "145" },
  { name: "ADONI", code: "146" },
  { name: "ALUR", code: "147" },
  { name: "RAYADURG", code: "148" },
  { name: "URAVAKONDA", code: "149" },
  { name: "GUNTAKAL", code: "150" },
  { name: "TADPATRI", code: "151" },
  { name: "SINGANAMALA", code: "152" },
  { name: "ANANTAPUR URBAN", code: "153" },
  { name: "KALYANDURG", code: "154" },
  { name: "RAPTADU", code: "155" },
  { name: "MADAKASIRA", code: "156" },
  { name: "HINDUPUR", code: "157" },
  { name: "PENUKONDA", code: "158" },
  { name: "PUTTAPARTHI", code: "159" },
  { name: "DHARMAVARAM", code: "160" },
  { name: "KADIRI", code: "161" },
  { name: "THAMBALLAPALLE", code: "162" },
  { name: "PILERU", code: "163" },
  { name: "MADANAPALLE", code: "164" },
  { name: "PUNGANUR", code: "165" },
  { name: "CHANDRAGIRI", code: "166" },
  { name: "TIRUPATI", code: "167" },
  { name: "SRIKALAHASTI", code: "168" },
  { name: "SATYAVEDU", code: "169" },
  { name: "NAGARI", code: "170" },
  { name: "GANGADHARA NELLORE", code: "171" },
  { name: "CHITTOOR", code: "172" },
  { name: "PUTHALAPATTU", code: "173" },
  { name: "PALAMANER", code: "174" },
  { name: "KUPPAM", code: "175" },
];

[
  { name: "Select District", code: "" },
  { name: "Araku", code: "01" },
  { name: "Srikakulam", code: "02" },
  { name: "Vizianagaram", code: "03" },
  { name: "Visakhapatnam", code: "04" },
  { name: "Anakapalli", code: "05" },
  { name: "Kakinada", code: "06" },
  { name: "Amalapuram", code: "07" },
  { name: "Rajahmundry", code: "08" },
  { name: "Narasapuram", code: "09" },
  { name: "Eluru", code: "10" },
  { name: "Machilipatnam", code: "11" },
  { name: "Vijayawada", code: "12" },
  { name: "Guntur", code: "13" },
  { name: "Narasaraopet", code: "14" },
  { name: "Bapatla", code: "15" },
  { name: "Ongole", code: "16" },
  { name: "Nandyal", code: "17" },
  { name: "Kurnool", code: "18" },
  { name: "Anantapur", vacode: "19" },
  { name: "Hindupur", vcode: "20" },
  { name: "Kadapa", code: "21" },
  { name: "Nellore", code: "22" },
  { name: "Tirupati", code: "23" },
  { name: "Rajampet", code: "24" },
  { name: "Chittoor", code: "25" },
];
